name: SPA
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - tmalign=20170708
  - tn93=1.0.13
  - seqkit=2.8.1
  - tqdm
  - altair
  - sklearn
  - ete3
  - altair
  - matplotlib
  - vl-convert-python

